# -*- coding: utf-8 -*-
"""ultah_diandra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Euy9phZYpfAJY1FNzdBacVsPxuYFP6lm
"""

import time

def nyanyi_ulang_tahun():
    nama = input("siapa nihh yang ulang tahun hari ini? ")
    harapan = input(f"Apa harapan {nama} di hari spesial ini? ")

    print("\nayo nyanyi lagu ultah duluu\n")

    time.sleep(1)
    print(f"Happy birthday to you... 🎶")
    time.sleep(2)
    print(f"Happy birthday to you... 🎶")
    time.sleep(2)
    print(f"Happy birthday dear {nama}... 🎶")
    time.sleep(2)
    print("Happy birthday to you! 🎉")

    print("\n💫 Harapanmu: ", harapan + " dan jadian sama Zulfahmi, aamiin. 🙏")

    # Ucapan dari aku
    time.sleep(1.5)
    print(f"\n🥳 Dari yujin: Semoga {nama} selalu bahagia, sehat, sukses dalam semua hal, dilancarin rezekinya!")
    print("\nBtw gue beliin kado bantal portable, biar lu gak lupa buat istirahat dimanapun :) semangat tekkomnya!")
    print(f"\n🎈 Happy Birthday, {nama} lovee! 🎉")

nyanyi_ulang_tahun()